language: scala
before_script:
- if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then gpg --import key.gpg; fi
script:
- sbt clean compile test
before_cache:
- find $HOME/.ivy2 -name "ivydata-*.properties" -print -delete
- find $HOME/.sbt  -name "*.lock"               -print -delete
cache:
  directories:
  - "$HOME/.cache/coursier"
  - "$HOME/.ivy2/cache"
  - "$HOME/.sbt"
deploy:
  provider: script
  cleanup: true
  script: bash scripts/deploy.sh
  on:
    tags: true
before_install:
- if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then openssl aes-256-cbc -K $encrypted_37d7bee1060c_key -iv $encrypted_37d7bee1060c_iv -in key.gpg.enc -out key.gpg -d; fi
